const ghosts = [
  { name: '火符鬼—惊讶', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/fire_amaze.gif' },
  { name: '火符鬼—生气', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/fire-angry.gif' },
  { name: '火符鬼—哭泣', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/fire-cry.gif' },
  { name: '火符鬼—悠闲', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/fire-free.gif' },
  { name: '火符鬼—睡觉', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/fire-sleep.gif' },
  { name: '火符鬼—思考', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/fire-think.gif' },
  { name: '金符鬼—惊讶', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/gold-amaze.gif' },
  { name: '金符鬼—生气', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/gold-angry.gif' },
  { name: '金符鬼—哭泣', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/gold-cry.gif' },
  { name: '金符鬼—悠闲', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/gold-free.gif' },
  { name: '金符鬼—睡觉', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/gold-sleep.gif' },
  { name: '金符鬼—思考', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/gold-think.gif' },
  { name: '土符鬼-惊讶', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/soil-amaze.gif' },
  { name: '土符鬼-生气', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/soil-angry.gif' },
  { name: '土符鬼-哭泣', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/soil-cry.gif' },
  { name: '土符鬼-悠闲', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/soil-free.gif' },
  { name: '土符鬼-睡觉', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/soil-sleep.gif' },
  { name: '土符鬼-思考', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/soil-think.gif' },
  { name: '水符鬼-惊讶', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/water-amaze.gif' },
  { name: '水符鬼-生气', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/water-angry.gif' },
  { name: '水符鬼-哭泣', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/water-cry.gif' },
  { name: '水符鬼-悠闲', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/water-free.gif' },
  { name: '水符鬼-睡觉', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/water-sleep.gif' },
  { name: '水符鬼-思考', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/water-think.gif' },
  { name: '木符鬼-惊讶', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/wood-amaze.gif' },
  { name: '木符鬼-生气', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/wood-angry.gif' },
  { name: '木符鬼-哭泣', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/wood-cry.gif' },
  { name: '木符鬼-悠闲', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/wood-free.gif' },
  { name: '木符鬼-睡觉', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/wood-sleep.gif' },
  { name: '木符鬼-思考', path: 'https://files.swdwiki.com/tos-cn-i-8vrofckkw9/emoji/wood-think.gif' },
];

export default ghosts;
